### PR TITLE
Update market detail loading with skeleton animation

### PR DESCRIPTION
**Pull request by hadi-norouzi**
#161

### CODE REVIEW

**Comment by Kaaveh** [comment]
Hey @hadi-norouzi , Thanks for your PR!
Please run `gradlew lintKotlin` for showing you the formatting issues.

**Comment by Kaaveh** [comment]
Like [this](https://github.com/Kaaveh/ComposeNews/pull/118#issuecomment-1746866260)

**Comment by Kaaveh** [comment]
Thanks for fixing.
Could you please add a screenshot to this PR description?

**Comment by hadi-norouzi** [comment]
Sure, i will.

**Comment by hadi-norouzi** [comment]
I update the detail page with a scrollable column when it's in landscape mode.
Screenshot 2023-11-13 at 12 30 37 PM

**Review by Kaaveh — APPROVED** [review]

**Comment by Kaaveh** [comment]
Amazing! Thanks for your contribution! We hope to see more PR from you! 🤩🙌🏻
close #161

**Comment by hadi-norouzi** [comment]
> Amazing! Thanks for your contribution! We hope to see more PR from you! 🤩🙌🏻 close #161

I hope so. 😉
Now you can close #161 issue.

**Pull request merged**
