### PR TITLE
add MarketDetail in MarketDetailScreen

### PR DESCRIPTION
**Pull request by hossein69ameri**

### CODE REVIEW

**Comment by VahidGarousi** [comment]
@hossein69ameri Hi, dear Hossein
Unfortunately, you have a merge conflict,
Please resolve it

**Comment by hossein69ameri** [comment]
Hi Dear Vahid, @VahidGarousi How should I solve it?

**Comment by hossein69ameri** [comment]
When I try to push it, it gives this error
FAILURE: Build failed with an exception. * What went wrong: Execution failed for task ':build-logic:convention:compileKotlin'. > 'compileJava' task (current target is 17) and 'compileKotlin' task (current target is 18) jvm target compatibility should be set to the same Java version. Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. * Get more help at https://help.gradle.org BUILD FAILED in 2s FAILURE: Build failed with an exception. * What went wrong: Execution failed for task ':build-logic:convention:compileKotlin'. > 'compileJava' task (current target is 17) and 'compileKotlin' task (current target is 18) jvm target compatibility should be set to the same Java version. Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. * Get more help at https://help.gradle.org BUILD FAILED in 3s failed to push some refs to 'https://github.com/hossein69ameri/ComposeNews.git'

**Comment by VahidGarousi** [comment]
@hossein69ameri I will try to clone your repository to do a more detailed investigation

**Comment by VahidGarousi** [comment]
What is your android studio jdk version? is that 17 or later?

**Comment by hossein69ameri** [comment]
17

**Comment by VahidGarousi** [comment]
Can you open your PR again? i want to check something

**Pull request closed without merging**
